name = "anthropic-gemini-adapter"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[env.production.vars]
# Add your Gemini API key as a secret: wrangler secret put GEMINI_API_KEY
# GEMINI_API_KEY = "your-gemini-api-key-here"

[env.production]
name = "anthropic-gemini-adapter"

[env.development]
name = "anthropic-gemini-adapter-dev"